image: $CI_REGISTRY_IMAGE

stages:
  - build

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p $CI_BUILD_TOKEN $CI_REGISTRY

build:
  tags:
  - docker-kvm
  stage: build
  script:
    - make
