image: docker:latest
services:
  - docker:dind

stages:
  - build

variables:
  IMAGE_TAG: $CI_REGISTRY/mc911-2018-s1/group-2:docker

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p $CI_JOB_TOKEN $CI_REGISTRY
  - echo $CI_REGISTRY_USER
  - echo $CI_JOB_TOKEN
  - echo $CI_REGISTRY
  - docker pull $IMAGE_TAG

build:
  stage: build
  script:
    - make
